# Generated by Django 2.1.7 on 2019-02-19 21:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('orderList', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('listId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('todoCount', models.IntegerField()),
                ('doneCount', models.IntegerField()),
                ('createdWhen', models.DateField(default='2019-02-19')),
                ('todoOrderList', models.TextField(default='')),
                ('doneOrderList', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='TodoApp.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='belongingList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todoList', to='TodoApp.TodoList'),
        ),
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('listId', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='todoitem',
            unique_together={('content', 'belongingList')},
        ),
    ]
